### ISSUE TITLE
Can't specify quota when creating a bucket

### ISSUE THREAD

**Issue by yardenshoham** [pulumi/pulumi-minio#37]
### What happened?

When creating a bucket in the MinIO console, one may (optionally), specify a quota (e.g. 40Gi). I couldn't find a way to set a quota.

### Steps to reproduce

.

### Expected Behavior

There should be a property `quota` in the constructor.

### Actual Behavior

There isn't.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Hi yardenshoham, 
This doesn't look like it has been surfaced in the upstream terraform provider, it will need to be added there: https://github.com/aminueza/terraform-provider-minio/blob/master/minio/resource_minio_s3_bucket.go and then when released it will be picked up in this provider.

**Comment by yardenshoham** [comment]
Ok, I'll post it there
