### ISSUE TITLE
S3Bucket.Quota should be `long` in C#

### ISSUE THREAD

**Issue by DillonN** [pulumi/pulumi-minio#449]
### Describe what happened

The `Quota` input field on the `S3Bucket` type is **in bytes** and should use `long` for C#:

https://github.com/pulumi/pulumi-minio/blob/ab80964e573e72164f8701ac226070e4284d6b6d/sdk/dotnet/S3Bucket.cs#L125-L126

With `int` like it is now, the [maximum value is 2^31 - 1](https://learn.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=net-8.0), or 2147483647, or ~2GB.

This is too small for buckets which can get into the terabyte range.

### Sample program

```csharp
// This works
var smallBucket = new S3Bucket(name, new()
{
    Bucket = "my-bucket",
    Quota = 10000000  // 10 MB
});

// This causes compile error:
// CS0266: Cannot implicitly convert type 'long' to 'Pulumi.Input<int>'. An explicit conversion exists (are you missing a cast?)	
var largeBucket = new S3Bucket(name, new()
{
    Bucket = "my-bucket",
    Quota = 10000000000  // 10 GB
});
```

### Affected Resource(s)

S3Bucket

### Output of `pulumi about`

```
CLI
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME         VERSION
resource  command      0.9.2
resource  crds         0.5.51
language  dotnet       unknown
resource  kubernetes   4.9.0
resource  minio        0.15.4
resource  random       4.16.1
resource  time         0.0.17

Host
OS       Microsoft Windows 11 Pro
Version  10.0.26120 Build 26120
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='8.0.400-preview.0.24324.5'

Current Stack: <redacted>

Found no resources associated with <redacted>

Found no pending operations associated with <redacted>

Backend
Name           pulumi.com
URL            <redacted>
User           <redacted>
Organizations  <redacted>
Token type     <redacted>

Dependencies:
NAME                    VERSION
<redacted>
<redacted>
<redacted>
```

### Additional context

Unable to find a workaround aside from manually adjusting quotas after apply.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @DillonN. Thanks for reporting this issue. We'll change the type of this field for the next release.

Related to https://github.com/pulumi/pulumi/issues/14242

**Comment by DillonN** [comment]
Thank you @iwahbe for the quick turnaround!
